# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: kubectl-pfw

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/kubectl-pfw/main.go
    binary: kubectl-pfw
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch

brews:
  - repository:
      owner: roeyazroel
      name: homebrew-tap
    description: "A kubectl plugin for port-forwarding multiple services or pods at once"
    homepage: "https://github.com/roeyazroel/kubectl-pfw"
    license: "MIT"
    test: |
      system "#{bin}/kubectl-pfw --version"
    install: |
      bin.install "kubectl-pfw"

krews:
  - name: pfw
    short_description: "Port-forward multiple services or pods at once"
    description: |
      A kubectl plugin for port-forwarding multiple services or pods simultaneously.
      Select and port-forward multiple services or pods with an interactive interface.
    homepage: "https://github.com/roeyazroel/kubectl-pfw"
    repository:
      owner: roeyazroel
      name: kubectl-pfw
